### ISSUE TITLE
paper manuscript

### ISSUE THREAD

**Issue by yujialele** [zyong812/STIP#1]
Thank you for good work. I'm very interested in it and want to learn the details of STIP model. Please provide the manuscript. Thanks!

**Comment by Panda-Peter** [comment]
Pls check the paper in this link:
https://openaccess.thecvf.com/content/CVPR2022/papers/Zhang_Exploring_Structure-Aware_Transformer_Over_Interaction_Proposals_for_Human-Object_Interaction_Detection_CVPR_2022_paper.pdf
