### ISSUE TITLE
 Interaction Proposal Network

### ISSUE THREAD

**Issue by leijue222** [zyong812/STIP#14]
In [STIP](https://github.com/zyong812/STIP/blob/930d6996a50e81d509a4f4bc7c96539b427d528f/src/models/stip.py#L126), which line code is the output of  **Interaction Proposal Network**?

**Comment by zyong812** [comment]
https://github.com/zyong812/STIP/blob/930d6996a50e81d509a4f4bc7c96539b427d528f/src/models/stip.py#L156
https://github.com/zyong812/STIP/blob/930d6996a50e81d509a4f4bc7c96539b427d528f/src/models/stip.py#L175
