### ISSUE TITLE
can't reproduce result.

### ISSUE THREAD

**Issue by OreoChocolate** [zyong812/STIP#17]
Hi, thanks for your remarkable work!

I have been attempting to reproduce the v-coco results in Table 3.
But, the STIP variations show about 1 AP lower results when compared to the reported results.

I have included my results here.
+HM+TR^SS | 63.99 | 68.6
+HM+TR^SC | 63.88 | 68.17
+HM+TR^{SS+SC} | 65.22 | 70.59

Would it be feasible for you to suggest a seed or provide some advice on how I can reproduce the reported results?
Thank you in advance!

**Comment by zyong812** [comment]
hi, how about using different learning rates?

**Comment by OreoChocolate** [comment]
Thanks for replying!

I tried changing the learning rates to train the model and got similar results reported in your paper.
