### ISSUE TITLE
pretrained models

### ISSUE THREAD

**Issue by WXLL579** [zyong812/STIP#2]
Thx for your excellent work!
Could you please provide the best model for hico-det and vcoco datasets? thx!

**Comment by WXLL579** [comment]
It takes large time to train, could you please provide the best model? thxxxx very much!!!

**Comment by zyong812** [comment]
Hi @WXLL579 ,

How long does it take for you training? If you follow README instructions, ~1-day training will be enough, and it will be easy to reproduce the results.

Or, you can test with following pretrained models:
* [VCOCO](https://cuhko365-my.sharepoint.com/:u:/g/personal/218019030_link_cuhk_edu_cn/EZyYzmW7vL9Bh7zKwT1JGFEBKbTkbs4vD9QW7kfs8EV_gQ?e=BamG9C)
* [HICO-DET (w/o jointly finetune)](https://cuhko365-my.sharepoint.com/:u:/g/personal/218019030_link_cuhk_edu_cn/ETPIGJHooGVPuOXDBC3WTaoBQBGHXioj4hAbjllSTSOn6A?e=gF5HyP)

**Comment by WXLL579** [comment]
thx!! The slow training is caused by our machine, we use one 1080 (ㄒoㄒ).

**Comment by WXLL579** [comment]
Is there a pretrained model through Jointly fine-tune object detector & HOI detector on HICO-DET? As shown in Table 2.
STIP (Ours) R50 A+S+L 32.22 28.15 33.43 35.29 31.43 36.45
Thanks!
