### ISSUE TITLE
The link for list_action.txt expired

### ISSUE THREAD

**Issue by MW-ZHOU** [zyong812/STIP#20]
Hi,
The link for list_action.txt expired, can you please upload the file again? Thanks a lot.

**Comment by zyong812** [comment]
I notice that some download links are broken. I've uploaded my archived data, especially for hico_20160224_det at https://cuhko365-my.sharepoint.com/:u:/g/personal/218019030_link_cuhk_edu_cn/EY3AbysMMUBJmQEt8zl4j9UBxHH6no2-g4o63EIt38GkgQ?e=ZPJajo
