### ISSUE TITLE
Does the object detector have to be DETR? 

### ISSUE THREAD

**Issue by wjtan99** [zyong812/STIP#7]
Thanks for your great work. 
Does the object detector have to be DETR? We are looking at your STIP on a custom dataset. However, we find that DETR is very hard to train. The typical problem is, after quite some training epochs, the mAP is still nearly 0. We find this is a very common problem in the issues of Facebookresearch/detr. Other than saying the training may take very long, there is really not good suggestions.  I read your paper, but just want your confirmation, does the object detector have to the DETR? Can it be replaced with Faster-RCNN?

**Comment by zyong812** [comment]
Thanks for your interest. You can replace DETR part in STIP with Faster-RCNN, and only use our interaction detection part of STIP. As for hard training of DETR, finetuning from a COCO-pretrained checkpoint will be easier, or using improved versions of DETR, e.g., Deformable-DETR.
