### ISSUE TITLE
About the conditions to use the code

### ISSUE THREAD

**Issue by tomotake-sasaki** [zyong812/STIP#9]
Thank you very much for sharing the source code of your great work! 

Currently, this repository does not contain the LICENSE file (unlike the repositories of DETR and HOTR, which this repository is stated  to be based on). Could you add it so that we could know the conditions to use the code?

**Comment by zyong812** [comment]
Thanks for reminding. We have updated the license.

**Comment by tomotake-sasaki** [comment]
I appreciate your prompt response!
